language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
before_script:
  - psql -c 'create database enju_oai_dummy_test;' -U postgres
  - psql enju_oai_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: FA7F9uAjzRWSLA8Pt0bdLuIF0RRNyj7exiDwbQbI5sCqRe/sbggKVDmZ/n/ndArEmA4Ca2WUveHnuucmBSmkgtU3eOU+cRK113YibtX9RW+QlGkuE05qDWROAAyCMotmp1fYSYyXQCAF4ZGC5Vhatf2BAJ7XK8fHbMuin/BLwMA=
sudo: false
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
jdk:
  - openjdk8
dist: xenial
