language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.1.9
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.2.5
    gemfile: gemfiles/rails_3.2.gemfile
notifications:
  slack:
    secure: FA7F9uAjzRWSLA8Pt0bdLuIF0RRNyj7exiDwbQbI5sCqRe/sbggKVDmZ/n/ndArEmA4Ca2WUveHnuucmBSmkgtU3eOU+cRK113YibtX9RW+QlGkuE05qDWROAAyCMotmp1fYSYyXQCAF4ZGC5Vhatf2BAJ7XK8fHbMuin/BLwMA=
sudo: false
