language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: FA7F9uAjzRWSLA8Pt0bdLuIF0RRNyj7exiDwbQbI5sCqRe/sbggKVDmZ/n/ndArEmA4Ca2WUveHnuucmBSmkgtU3eOU+cRK113YibtX9RW+QlGkuE05qDWROAAyCMotmp1fYSYyXQCAF4ZGC5Vhatf2BAJ7XK8fHbMuin/BLwMA=
sudo: false
